### ISSUE TITLE
Find out which things are autoinstrumented

### ISSUE THREAD

**Issue by etiennea** [hyperdxio/hyperdx-js#67]
I am not seeing PG instrumentation, not sure how to make sure it is loaded.

**Comment by MikeShi42** [comment]
Since we depend on otel's node auto instrumentation package, the list should be largely the same: https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node#supported-instrumentations. Though agreed, this should be documented at a more top-level.

That being said, pg should be part of the list so weird that you're not seeing it loaded (but I assume other instrumentations are working?)
